/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_petrsu_cardiacare_smartcarevolunteer_MainActivity */

#ifndef _Included_com_petrsu_cardiacare_smartcarevolunteer_MainActivity
#define _Included_com_petrsu_cardiacare_smartcarevolunteer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    connectSmartSpace
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jlong JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_connectSmartSpace
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    disconnectSmartSpace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_disconnectSmartSpace
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    initVolunteer
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_initVolunteer
  (JNIEnv *, jobject, jlong);

JNIEXPORT jint JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_insertPersonName
        (JNIEnv *, jobject, jlong, jstring, jstring);

JNIEXPORT void JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_removeIndividual
(JNIEnv*, jobject, jlong, jstring);

JNIEXPORT jstring JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_initAuthRequest
        (JNIEnv *, jobject , jlong , jstring );

JNIEXPORT jint JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_getAuthResponce
        (JNIEnv *, jobject , jlong , jstring );

JNIEXPORT jint JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_updatePersonName
        (JNIEnv *, jobject , jlong , jstring , jstring );


JNIEXPORT jint JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_setVolunteerStatus
        (JNIEnv *, jobject , jlong , jstring , jstring );
/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    initLocation
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_initLocation
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    sendLocation
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_sendLocation
        (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    initPatientListSbscr
 * Signature: (J)I
 */
JNIEXPORT jlong JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_initPatientListSbscr
        (JNIEnv *, jobject , jlong , jstring);

JNIEXPORT jlong JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_helpRequestAnswer
        (JNIEnv *, jobject , jlong , jstring , jstring);


JNIEXPORT jstring JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_getPatientUriWithAlarm
        (JNIEnv *, jobject , jlong , jstring);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    updatePatientList
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_updatePatientList
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    stopPatientListSbscr
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_stopPatientListSbscr
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    initAlarmSbcr
 * Signature: (J)I
 */
JNIEXPORT jlong JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_initAlarmSbcr
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    updateAlarmList
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_updateAlarmList
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_petrsu_cardiacare_smartcarevolunteer_MainActivity
 * Method:    stopAlarmListSbcr
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_stopAlarmListSbcr
  (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_initCurrentPatientLocationSbcr
        (JNIEnv *, jobject, jlong, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_petrsu_cardiacare_smartcarevolunteer_MainActivity_PatientListTask */

#ifndef _Included_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_PatientListTask
#define _Included_com_petrsu_cardiacare_smartcarevolunteer_MainActivity_PatientListTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
